import * as defaultFlash from "./local-flash.mjs";
import {loadHostedRelease,selectHostedTarget} from "./hosted-release.mjs";
import {chipFamily} from "./safety-contract.mjs";
import {createDiagnoseRuntime,diagnosePresentation} from "./diagnose.mjs";
import {createP2PSeedRuntime} from "./p2p-seed.mjs";

const INSTALL_ACTIONS={"quinled-dig2go":"Install Dig2Go firmware","athom-c3-tubes":"Install Athom C3 firmware","waveshare-s3-tubes-remote":"Install Waveshare S3 firmware"};
const CONNECT_ACTIONS={"quinled-dig2go":"Connect Dig2Go","athom-c3-tubes":"Connect Athom C3","waveshare-s3-tubes-remote":"Connect Waveshare S3"};
const shortTarget=id=>({"quinled-dig2go":"Dig2Go","athom-c3-tubes":"Athom C3","waveshare-s3-tubes-remote":"Waveshare S3"}[id]||id);

/** Render the complete Flash shell. No async helper may mutate Flash visibility directly. */
export function renderFlashState(ui,state,payload={}) {
  const compatibility=["unsupported","insecure"].includes(state),choose=state==="choose",connected=state==="connected",mismatch=state==="mismatch",recovery=mismatch&&payload.connectedChip&&payload.connectedTargetId,result=["success","error"].includes(state)||(mismatch&&!recovery),browserIssue=compatibility?payload.browserIssue:null;
  const set=(node,hidden)=>{if(node)node.hidden=hidden};
  set(ui.hero,compatibility||connected||result||recovery);set(ui.installCard,compatibility||result||recovery);set(ui.deviceSelect,!choose&&!recovery);set(ui.options,!choose&&!recovery);set(ui.state,choose||result);set(ui.advanced,!choose&&!recovery);set(ui.mismatchRecovery,!recovery);
  set(ui.connect,!choose||Boolean(browserIssue));set(ui.recommendation,!choose);set(ui.install,!connected);set(ui.back,!connected);set(ui.actionNote,true);set(ui.result,!result);set(ui.gate,!browserIssue);
  if(compatibility){for(const node of [ui.rail,ui.title,ui.instruction,ui.deviceSelect,ui.state,ui.connect,ui.install,ui.back,ui.actionNote,ui.advanced,ui.result])set(node,true);set(ui.installCard,false);set(ui.gate,false);}
  const active=state==="choose"?0:state==="connecting"?1:state==="connected"?2:3;
  ui.steps?.forEach((step,i)=>{step.removeAttribute?.("aria-current");if(i===active)step.setAttribute?.("aria-current","step");});
  if(ui.title)ui.title.textContent=result?(state==="success"?"Firmware installed":state==="verifying"?"Almost done":"Install needs attention"):state==="connected"?`${shortTarget(payload.targetId)} connected`:state==="choose"?"Install firmware":state==="connecting"?"Connecting":state==="finishing"?"Finishing installation":"Installing";
  if(ui.instruction)ui.instruction.textContent=choose?"Select the controller you plugged in. Chrome will ask which USB device to use.":payload.instruction||"";
  if(ui.status)ui.status.textContent=payload.status||"";
  if(ui.state)ui.state.className=`status-banner ${payload.tone||"neutral"}`;
  if(ui.stateTitle)ui.stateTitle.textContent=payload.stateTitle||({connecting:"Connecting to controller",installing:"Installing firmware",finishing:"Restarting and checking"}[state]||"");
  if(ui.gateMessage)ui.gateMessage.textContent=browserIssue||"";
  if(ui.gateTitle)ui.gateTitle.textContent=state==="insecure"?"Easy Flash needs a secure connection":"Easy Flash needs Chrome or Edge";
  if(ui.connect)ui.connect.textContent=choose?(CONNECT_ACTIONS[payload.selectedId]||"Connect"):"Connect";
  if(ui.connect)ui.connect.disabled=Boolean(browserIssue);
  if(ui.install){ui.install.textContent=payload.propagating||/propagating image/i.test(payload.status||"")?"Install propagating Dig2Go firmware":INSTALL_ACTIONS[payload.targetId]||"Install";ui.install.disabled=!connected;}
  if(ui.resultTitle)ui.resultTitle.textContent=state==="success"?"You did it!":state==="mismatch"?"Installed firmware did not match":"Install stopped";
  if(ui.resultMessage)ui.resultMessage.textContent=payload.message||"";
  if(ui.resultNext)ui.resultNext.textContent=payload.next||"";
  set(ui.resultDiagnose,state!=="mismatch");
  if(ui.resultDiagnose){ui.resultDiagnose.className="primary";ui.resultDiagnose.textContent="Diagnose controller";}
  set(ui.resultVerify,true);
  if(ui.resultVerify){ui.resultVerify.className="primary";ui.resultVerify.textContent="Check again";}
  if(ui.resultDone){ui.resultDone.hidden=!result;ui.resultDone.className=state==="mismatch"||state==="verifying"?"secondary":"primary";ui.resultDone.textContent=state==="success"?"Hooray — done!":"Done";}
  if(ui.resultSeed)ui.resultSeed.hidden=state!=="success"||!payload.seedAvailable;
  if(ui.result)ui.result.className=`result-panel ${payload.tone||(state==="success"?"positive":state==="verifying"?"neutral":"attention")}`;
  if(ui.mismatchFacts)ui.mismatchFacts.textContent=mismatch?`Selected: ${payload.selectedLabel||payload.selectedId||"unknown"} · Connected: ${payload.connectedLabel||payload.connectedChip||"unknown"}`:"";
  if(ui.mismatchReason)ui.mismatchReason.textContent=mismatch?(payload.reason||"The selected target and connected chip family do not agree. Nothing was written."):"";
  if(ui.useConnected){ui.useConnected.hidden=!mismatch||!payload.connectedTargetId;ui.useConnected.disabled=!payload.connectedTargetId;ui.useConnected.textContent=payload.connectedTargetId?`Use ${payload.connectedLabel||"connected device"}`:"Use connected device unavailable";}
}

export function initEasyFlash({document:doc=document,navigator:navigatorRef=globalThis.navigator,isSecureContext=globalThis.isSecureContext,releaseLoader=loadHostedRelease,fetchImpl=globalThis.fetch,flash=defaultFlash,diagnoseRuntime=createDiagnoseRuntime({serial:navigatorRef?.serial}),seedRuntime=createP2PSeedRuntime()}={}) {
 const $=s=>doc.querySelector(s),ui={hero:$(".hero"),rail:$(".state-rail"),recommendation:$("#recommendation"),connect:$("#connect"),connectPropagating:$("#connectPropagating"),otaDownloads:$("#otaDownloads"),back:$("#back"),install:$("#install"),gate:$("#browserGate"),gateTitle:$("#browserGateTitle"),gateMessage:$("#browserGateMessage"),options:$("#deviceOptions"),deviceSelect:$("#deviceSelect"),installCard:$(".install-card"),mismatchRecovery:$("#mismatchRecovery"),mismatchFacts:$("#mismatchFacts"),mismatchReason:$("#mismatchReason"),useConnected:$("#useConnected"),chooseAnother:$("#chooseAnother"),changeTarget:$("#changeTarget"),steps:[...(doc.querySelectorAll?.(".state-rail span")||[])],state:$("#controllerState"),stateTitle:$("#controllerStateTitle"),status:$("#controllerStatus"),title:$("#installTitle"),instruction:$("#instruction"),advanced:$("#advancedDetails"),actionNote:$("#actionNote"),result:$("#resultPanel"),resultTitle:$("#resultTitle"),resultMessage:$("#resultMessage"),resultNext:$("#resultNext"),resultDone:$("#resultDone"),resultSeed:$("#resultSeed"),resultDiagnose:$("#resultDiagnose"),resultVerify:$("#resultVerify")};
 const diagnose={inspect:$("#diagnoseInspect"),state:$("#diagnoseState"),title:$("#diagnoseTitle"),message:$("#diagnoseMessage"),technical:$("#diagnoseTechnical"),facts:$("#diagnoseFacts")};const tabs=[$("#flashTab"),$("#diagnoseTab"),$("#statusTab")].filter(Boolean),views=[$("#flashView"),$("#diagnoseView"),$("#statusView")].filter(Boolean);
 let release=null,selection=null,pendingVerify=null,seedBinding=null,installMode="ordinary",state="choose",statePayload={};
 const browserIssue=()=>{if(!isSecureContext)return "Easy Flash must be opened over HTTPS. Reopen this exact URL over HTTPS in Chrome or Edge on a computer.";const ua=String(navigatorRef?.userAgent||"").toLowerCase();return (/safari/.test(ua)&&!/chrome|crios|edg/.test(ua))||/firefox|fxios/.test(ua)||!navigatorRef?.serial?.requestPort?"This browser cannot connect to the controller. Reopen this exact URL in Chrome or Edge on a computer.":null;};
 const transition=(next,payload={})=>{state=next;statePayload={...payload,browserIssue:browserIssue()};doc.documentElement?.setAttribute?.("data-browser-state",next);renderFlashState(ui,next,statePayload);};
 function renderOptions(catalog){if(!ui.options)return;ui.options.replaceChildren(...catalog.map(({variant})=>{const label=doc.createElement("label"),input=doc.createElement("input"),span=doc.createElement("span"),strong=doc.createElement("strong"),small=doc.createElement("small");label.className="device-option";input.type="radio";input.name="deviceChoice";input.value=variant.id;input.checked=variant.id==="quinled-dig2go";strong.textContent=variant.target.printedModel;small.textContent=`Tubes v${variant.bootIdentity.tubes}`;span.append(strong,small);label.append(input,span);input.addEventListener("change",()=>transition(state,{...statePayload,selectedId:input.value}));return label;}));}
 const selected=()=>selectHostedTarget(release.catalog,ui.options?.querySelector?.("input[name=deviceChoice]:checked")?.value||"quinled-dig2go");
 async function connect(){if(!release)return;transition("connecting",{status:"Choose the USB device in Chrome…",tone:"neutral"});try{const evidence=await flash.connectToController({onStatus:status=>transition("connecting",{status,tone:"neutral"})});let chosen=installMode==="propagating"?selectHostedTarget(release.catalog,"quinled-dig2go"):selected();if(installMode==="propagating"){if(!chosen.propagatingArtifact)throw Error("The immutable propagating Dig2Go image is unavailable");chosen={...chosen,artifact:chosen.propagatingArtifact};}const family=chipFamily(evidence.chipName),match=release.catalog.find(({variant})=>chipFamily(variant.target.chip)===family);if(family!==chipFamily(chosen.variant.target.chip)){selection=null;transition("mismatch",{selectedId:chosen.variant.id,selectedLabel:chosen.variant.target.printedModel,connectedChip:evidence.chipName,connectedTargetId:match?.variant.id,connectedLabel:match?.variant.target.printedModel,evidence,reason:match?"Choose the connected target only if its exact supported identity and canonical firmware are available.":"No canonical firmware is available for the connected target.",message:`Detected ${evidence.chipName} does not match selected ${chosen.variant.target.printedModel}. Nothing was written.`,tone:"attention"});return;}const canonical={releaseId:release.releaseId,...chosen,installMode};selection={...canonical,evidence:flash.bindConnectedController({evidence,variant:canonical.variant,artifact:canonical.artifact})};transition("connected",{targetId:canonical.variant.id,stateTitle:`${family} detected`,status:installMode==="propagating"?"Exact Dig2Go detected · propagating image explicitly selected":`Exact chip family: ${family}`,tone:"positive",instruction:installMode==="propagating"?"Confirm this is the one Dig2Go that should carry the explicit propagation baton. Nothing is written until you choose Install.":`Confirm the board says ${canonical.variant.target.printedModel}. Nothing is written until you choose Install.`});}catch(error){await flash.disconnectController?.();selection=null;if(error.name==="NotFoundError")transition("choose");else transition("error",{message:error.message,next:"Return to the chooser and check the selected controller.",tone:"attention"});}}
 async function useConnected(){const id=statePayload.connectedTargetId,evidence=statePayload.evidence;if(!id||!evidence||!release)return;const chosen=selectHostedTarget(release.catalog,id),family=chipFamily(evidence.chipName),canonical={releaseId:release.releaseId,...chosen};selection={...canonical,evidence:flash.bindConnectedController({evidence,variant:canonical.variant,artifact:canonical.artifact})};transition("connected",{targetId:canonical.variant.id,stateTitle:`${family} detected`,status:`Exact chip family: ${family}`,tone:"positive",instruction:`Confirm the board says ${canonical.variant.target.printedModel}. Nothing is written until you choose Install.`});}
 async function back(){await flash.disconnectController?.();selection=null;installMode="ordinary";transition("choose");}

 async function install(){
  if(!selection)return;
  const current=selection;seedBinding=null;transition("installing",{targetId:current.variant.id,status:"Writing firmware…",tone:"progress"});
  try{
   const actionLabel=current.installMode==="propagating"?"Install propagating Dig2Go firmware":INSTALL_ACTIONS[current.variant.id];
   const result=await flash.installConnectedController({variant:current.variant,artifact:current.artifact,sessionToken:current.evidence.token,port:current.evidence.port,candidateAction:{targetId:current.variant.id,label:actionLabel,artifactSha256:current.artifact.sha256,sessionToken:current.evidence.token,port:current.evidence.port},onStatus:status=>transition(/restart|verif|check|health/i.test(status)?"finishing":"installing",{targetId:current.variant.id,status,tone:"progress"}),onReceipt:()=>{},onProgress:p=>transition("installing",{targetId:current.variant.id,status:`Writing firmware… ${p}%`,tone:"progress"})});
   const verification=result.verification||{status:"verified"},verified=verification.status==="verified";
   seedBinding=current.installMode==="propagating"?seedRuntime.bind({port:verification.port||current.evidence.port,token:current.evidence.token,targetId:current.variant.id,verified}):null;
   if(verification.status==="mismatch")transition("mismatch",{message:"Easy Flash detected different firmware after the controller restarted. Nothing was rewritten.",next:"Use Diagnose controller to inspect it.",tone:"attention"});
   else if(seedBinding){
    transition("finishing",{targetId:current.variant.id,status:"Firmware verified. Waiting for the Dig2Go to start propagation…",tone:"progress"});
    try{
     const propagation=await seedRuntime.seed(seedBinding,{onStatus:status=>transition("finishing",{targetId:current.variant.id,status,tone:"progress"})});
     seedBinding=null;
     transition("success",{message:"Propagating firmware is installed and running.",next:propagation.acknowledged?"This Dig2Go accepted one serve turn. Power or wake the nearby receiver; the devices own the remaining transfer.":"The firmware was installed, but Easy Flash did not hear propagation acceptance. Choose Update nearby Dig2Gos to retry the command.",tone:propagation.acknowledged?"positive":"neutral",postbootVerification:verified,seedAvailable:!propagation.acknowledged});
    }catch(error){transition("success",{message:"Propagating firmware is installed.",next:`Automatic propagation did not start: ${error.message}`,tone:"neutral",postbootVerification:verified,seedAvailable:Boolean(seedBinding)});}
   }else transition("success",{message:"Firmware bytes were written successfully. The controller should restart.",next:current.installMode==="propagating"?"The propagating image could not be verified, so no propagation command was sent.":"This ordinary v51 image does not start peer propagation.",tone:current.installMode==="propagating"?"neutral":"positive",postbootVerification:verified,seedAvailable:false});
   selection=null;
  }catch(error){transition("error",{message:error.message,next:"Reconnect the controller and try again.",tone:"attention"});}
 }
 async function seedNearby(){if(!seedBinding)return;ui.resultSeed.disabled=true;try{const result=await seedRuntime.seed(seedBinding,{onStatus:message=>{ui.resultNext.textContent=message;}});seedBinding=null;transition("success",{message:"The propagation command was sent to the verified Dig2Go.",next:result.acknowledged?"This Dig2Go accepted one serve turn. Power or wake the nearby receiver; the devices own the remaining transfer.":"No serial acknowledgement was captured. No peer-update result is claimed; reinstall or verify and retry if needed.",tone:result.acknowledged?"positive":"neutral",seedAvailable:false});}catch(error){transition("success",{message:"Firmware remains installed; nearby-device propagation did not start.",next:error.message,tone:"neutral",seedAvailable:Boolean(seedBinding)});}finally{ui.resultSeed.disabled=false;}}
 async function checkAgain(){if(!pendingVerify)return;const current=pendingVerify;try{const {verification,retryToken}=await flash.verifyWrittenController({variant:current.variant,artifact:current.artifact,port:current.port,retryToken:current.retryToken});if(verification.status==="verified"){pendingVerify=null;transition("success",{message:"Firmware is installed and the controller restarted.",next:"Next, unplug USB, connect your lights, and power the controller normally. Then rave on.",tone:"positive"});}else if(verification.status==="mismatch"){pendingVerify=null;transition("mismatch",{message:"Easy Flash detected different firmware after the controller restarted. Nothing was rewritten.",next:"Use Diagnose controller to inspect it.",tone:"attention"});}else{pendingVerify=retryToken?{...current,retryToken}:null;transition("verifying",{message:"Still waiting — the controller hasn't confirmed its restart yet.",next:retryToken?"Make sure USB is still plugged in, wait a few seconds, then choose Check again.":"Use Diagnose controller to inspect it, or choose Done.",retryAvailable:Boolean(retryToken),tone:"neutral"});}}catch(error){pendingVerify=null;transition("error",{message:error.message,next:"Reconnect the controller and try again.",tone:"attention"});}}
 function done(){selection=null;pendingVerify=null;seedBinding=null;installMode="ordinary";transition("choose");ui.connect?.focus?.();}
 function diagnoseResult(){selectTab(tabs.find(t=>t.id==="diagnoseTab"));}
 async function inspect(){diagnose.inspect.disabled=true;diagnose.state.hidden=false;diagnose.state.className="status-banner neutral";diagnose.title.textContent="Reading USB report…";diagnose.message.textContent="";if(diagnose.technical)diagnose.technical.hidden=true;if(diagnose.facts){diagnose.facts.hidden=true;diagnose.facts.replaceChildren();}try{await flash.disconnectController?.();const result=await diagnoseRuntime.inspect({onStatus:message=>{diagnose.message.textContent=message;}}),view=diagnosePresentation(result);diagnose.state.className=`status-banner ${view.tone}`;diagnose.title.textContent=view.label;diagnose.message.textContent=view.summary;diagnose.inspect.textContent=view.action||"Choose USB device";const next=diagnose.state.parentElement?.querySelector?.(".diagnose-next");if(next)next.textContent=view.next;const records=[["Controller identity",result.target],["Target report",result.observedTarget],["Chip",result.chip],["Tubes generation",result.tubes],["Tubes version",result.version],["Rescue",result.rescue?"ACTIVE":"INACTIVE"],["Button",result.button],["Captured bytes",result.bytesCaptured]].filter(([,value])=>value!==null&&value!==undefined&&value!==""&&value!=="unknown"&&value!=="Unknown"&&value!==0);if(records.length&&diagnose.technical){diagnose.technical.hidden=false;diagnose.facts.hidden=false;diagnose.facts.replaceChildren(...records.map(([label,value])=>{const row=doc.createElement("p");row.textContent=`${label}: ${value}`;return row;}));}}catch(error){const cancelled=error.name==="NotFoundError";diagnose.state.className="status-banner yellow";diagnose.title.textContent=cancelled?"No USB device selected":"Report needs attention";diagnose.message.textContent=cancelled?"Nothing was opened or changed.":error.message;diagnose.inspect.textContent=cancelled?"Choose USB device":"Check another USB device";}finally{diagnose.inspect.disabled=false;}}
 function selectTab(tab){for(const t of tabs){t.setAttribute("aria-selected",String(t===tab));t.tabIndex=t===tab?0:-1;}for(const v of views)v.hidden=v.getAttribute("aria-labelledby")!==tab?.id;if(tab?.id!=="flashTab")selection=null;if(tab?.id==="statusTab")doc.dispatchEvent(new Event("easy-flash:status-selected"));}
 ui.chooseAnother?.addEventListener("click",connect);ui.changeTarget?.addEventListener("click",()=>transition("choose",{selectedId:statePayload.selectedId}));ui.useConnected?.addEventListener("click",useConnected);ui.connectPropagating?.addEventListener("click",()=>{installMode="propagating";connect();});tabs.forEach((t,index)=>{t.addEventListener("click",()=>selectTab(t));t.addEventListener("keydown",event=>{let next;if(event.key==="ArrowRight"||event.key==="ArrowLeft")next=(index+(event.key==="ArrowRight"?1:tabs.length-1))%tabs.length;else if(event.key==="Home")next=0;else if(event.key==="End")next=tabs.length-1;else return;event.preventDefault();tabs[next].focus();selectTab(tabs[next]);});});diagnose.inspect?.addEventListener("click",inspect);ui.connect?.addEventListener("click",()=>{installMode="ordinary";connect();});ui.back?.addEventListener("click",back);ui.install?.addEventListener("click",install);ui.resultDone?.addEventListener("click",done);ui.resultSeed?.addEventListener("click",seedNearby);ui.resultDiagnose?.addEventListener("click",diagnoseResult);ui.resultVerify?.addEventListener("click",checkAgain);flash.setInvalidationHandler?.(()=>{selection=null;seedBinding=null;installMode="ordinary";transition("choose");});
 transition(browserIssue()?(isSecureContext?"unsupported":"insecure"):"choose");if(browserIssue()&&diagnose.inspect){diagnose.inspect.disabled=true;diagnose.inspect.hidden=true;}releaseLoader({fetchImpl,baseUrl:doc.baseURI||import.meta.url}).then(v=>{release=v;renderOptions(v.catalog);if(ui.otaDownloads)ui.otaDownloads.replaceChildren(...v.catalog.map(item=>{const a=doc.createElement("a");a.href=item.otaArtifact.url;a.download="";a.textContent=`${shortTarget(item.variant.id)} ordinary v51 OTA`;a.dataset.sha256=item.otaArtifact.sha256;return a;}));}).catch(e=>transition("error",{message:e.message,tone:"attention"}));return {connect,install,checkAgain,inspect,selectTab,getSelection:()=>selection,renderFlashState:transition};
}
if(typeof document!=="undefined")initEasyFlash();
