const api=window.easyFlashFleet;
if(api){
 const host=document.querySelector("#technicalDetails"),baton=host?.querySelector(".baton-card"),card=document.createElement("section");
 card.id="fleetUpdateCard";card.innerHTML=`<strong>Laptop fleet OTA · ordinary v51</strong><p id="fleetSupport">Ready for a read-only scan through Steve’s bundled fleet helper. No update starts automatically.</p><div id="fleetControls"><label>Reachable laptop address <input id="fleetAdvertise" inputmode="decimal" placeholder="192.168.1.10"></label><div class="result-actions"><button type="button" class="secondary" id="fleetScan">Scan reachable Tubes</button><button type="button" class="primary" id="fleetUpdateSelected" disabled>Update selected</button><button type="button" class="secondary" id="fleetUpdateAll" disabled>Update all eligible</button></div><div id="fleetDevices" aria-live="polite"><p>No real device report received. Start remains disabled.</p></div></div>`;
 host?.insertBefore(card,baton||null);
 const support=card.querySelector("#fleetSupport"),list=card.querySelector("#fleetDevices"),scan=card.querySelector("#fleetScan"),start=card.querySelector("#fleetUpdateSelected"),all=card.querySelector("#fleetUpdateAll"),advertise=card.querySelector("#fleetAdvertise");let devices=[];
 const escape=value=>String(value??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
 function render(){list.innerHTML=devices.length?`<table><thead><tr><th></th><th>Device ID</th><th>Target</th><th>Current</th><th>Last heard</th><th>Artifact</th><th>State</th></tr></thead><tbody>${devices.map(d=>`<tr><td><input type="checkbox" data-mac="${escape(d.mac)}" ${d.eligible?"":"disabled"}></td><td>${escape(d.deviceId)}</td><td>${escape(d.model)}</td><td>v${escape(d.version)}</td><td>${escape(d.lastHeard)} · ${escape(d.reachability)}</td><td>${escape(d.artifact||"None")}</td><td>${escape(d.state)}</td></tr>`).join("")}</tbody></table>`:"<p>No real device report received. Start remains disabled.</p>";start.disabled=all.disabled=!devices.some(d=>d.eligible);}
 api.onEvent(event=>{const device=devices.find(d=>d.mac===event.mac);if(device){device.state=event.state;render();}});
 scan.addEventListener("click",async()=>{scan.disabled=true;try{const result=await api.scan();devices=result.devices;advertise.value=result.advertise||"";support.textContent=`${devices.length} real device report${devices.length===1?"":"s"} received.`;render();}catch(error){devices=[];support.textContent=`Scan failed closed: ${error.message}`;render();}finally{scan.disabled=false;}});
 const update=async macs=>{start.disabled=all.disabled=true;try{await api.update({advertise:advertise.value,deviceMacs:macs});}catch(error){support.textContent=`Update stopped: ${error.message}`;}finally{render();}};
 start.addEventListener("click",()=>update([...list.querySelectorAll("input:checked")].map(input=>input.dataset.mac)));all.addEventListener("click",()=>update(devices.filter(d=>d.eligible).map(d=>d.mac)));
}
