import assert from "node:assert/strict";
import test from "node:test";
import {initEasyFlash,renderFlashState} from "../app.mjs";
import {createDiagnoseRuntime,diagnosePresentation,parseDiagnosticText} from "../diagnose.mjs";

class Element {
	constructor(doc,id=""){this.doc=doc;this.id=id;this.hidden=false;this.disabled=false;this.checked=false;this.value="";this.textContent="";this.className="";this.listeners={};this.dataset={};this.attrs={};}
	addEventListener(type,handler){(this.listeners[type]??=[]).push(handler);}
	querySelector(selector){if(this.id==="deviceOptions")return (this.children||[]).flatMap(label=>label.children||[]).find(input=>input.type==="radio"&&((selector.includes(":checked")&&input.checked)||selector.includes("input[name=deviceChoice]")))||null;return this.doc.querySelector(selector);}
	dispatch(type,event={}){for(const handler of this.listeners[type]||[])handler({target:this,preventDefault(){},...event});}
	focus(){this.doc.activeElement=this;}
	append(...children){this.children=[...(this.children||[]),...children];} replaceChildren(...children){this.children=children;}
	setAttribute(name,value){this.attrs[name]=String(value);}
	removeAttribute(name){delete this.attrs[name];}
	getAttribute(name){return this.attrs[name]??null;}
}

test("renderFlashState owns the complete visibility, action, tone, and progress matrix",()=>{
	const doc={activeElement:null,querySelector(){return null;}},node=()=>new Element(doc),steps=Array.from({length:4},node),ui={installCard:node(),deviceSelect:node(),options:node(),state:node(),advanced:node(),connect:node(),install:node(),back:node(),actionNote:node(),result:node(),gate:node(),gateMessage:node(),steps,title:node(),instruction:node(),status:node(),stateTitle:node(),resultTitle:node(),resultMessage:node(),resultNext:node(),resultDone:node(),resultDiagnose:node(),resultVerify:node()};
	const cases={choose:{picker:true,status:false,advanced:true,connect:true,install:false,back:false,result:false,step:0},connecting:{picker:false,status:true,advanced:false,connect:false,install:false,back:false,result:false,step:1},connected:{picker:false,status:true,advanced:false,connect:false,install:true,back:true,result:false,step:2},installing:{picker:false,status:true,advanced:false,connect:false,install:false,back:false,result:false,step:3},finishing:{picker:false,status:true,advanced:false,connect:false,install:false,back:false,result:false,step:3},success:{picker:false,status:false,advanced:false,connect:false,install:false,back:false,result:true,step:3},mismatch:{picker:false,status:false,advanced:false,connect:false,install:false,back:false,result:true,step:3},error:{picker:false,status:false,advanced:false,connect:false,install:false,back:false,result:true,step:3}};
	for(const [state,want] of Object.entries(cases)){renderFlashState(ui,state,{targetId:"quinled-dig2go",status:`${state} status`,message:`${state} message`,tone:state==="success"?"positive":state==="mismatch"||state==="error"?"attention":"neutral"});assert.deepEqual({picker:!ui.deviceSelect.hidden,status:!ui.state.hidden,advanced:!ui.advanced.hidden,connect:!ui.connect.hidden,install:!ui.install.hidden,back:!ui.back.hidden,result:!ui.result.hidden,step:steps.findIndex(step=>step.attrs["aria-current"]==="step")},want,state);assert.equal(ui.install.disabled,state!=="connected",state);assert.equal(ui.resultDiagnose.hidden,state!=="mismatch",state);assert.equal(ui.resultVerify.hidden,true,state);}
});

function fixture() {
	const doc={activeElement:null,documentElement:{dataset:{}},nodes:{},listeners:{},baseURI:"https://flash.test/",querySelector(selector){return this.nodes[selector];},createElement(){return new Element(this);},addEventListener(type,handler){(this.listeners[type]??=[]).push(handler);},dispatchEvent(event){for(const handler of this.listeners[event.type]||[])handler(event);}};
	for(const id of ["deviceOptions","connect","connectPropagating","install","back","mismatchRecovery","mismatchFacts","mismatchReason","useConnected","chooseAnother","changeTarget","browserGate","browserGateTitle","browserGateMessage","controllerState","controllerStateTitle","controllerStatus","installTitle","instruction","actionNote","technicalDetails","resultPanel","resultTitle","resultMessage","resultNext","resultDone","resultSeed","resultDiagnose","resultVerify","flashTab","diagnoseTab","statusTab","flashView","diagnoseView","statusView","diagnoseInspect","diagnoseState","diagnoseTitle","diagnoseMessage","diagnoseTechnical","diagnoseFacts"])doc.nodes[`#${id}`]=new Element(doc,id);
	for(const id of ["flashView","diagnoseView","statusView"])doc.nodes[`#${id}`].attrs["aria-labelledby"]=`${id.replace("View","Tab")}`;
	for(const id of ["install","actionNote","resultPanel","diagnoseView","statusView","diagnoseFacts"])doc.nodes[`#${id}`].hidden=true;doc.nodes["#browserGateTitle"].textContent="Easy Flash needs Chrome or Edge";
	const targets=[["quinled-dig2go","QuinLED Dig2Go","ESP32"],["athom-c3-tubes","Athom ESP32-C3 controller","ESP32-C3"],["waveshare-s3-tubes-remote","Waveshare ESP32-S3-Touch-AMOLED-2.16","ESP32-S3"]];
	const catalog=targets.map(([id,printedModel,chip])=>({variant:{id,label:printedModel,source:{commit:"a".repeat(40)},bootIdentity:{version:1,target:id,source:"a".repeat(40),release:"16.0.1",tubes:14},target:{printedModel,board:printedModel,chip}},artifact:{url:`https://flash.test/${id}.bin`,sha256:id.padEnd(64,"a")}}));
	catalog[0].propagatingArtifact={url:"https://flash.test/quinled-dig2go-propagating.bin",sha256:"p".repeat(64),transport:"usb-propagating"};
	let installs=0,connects=0,verifies=0,disconnects=0,seeds=0,invalidator,lastArgs,lastVerifyArgs,inspects=0,connectError=null,verificationStatus="verified";
	const resultFor=(variant,status)=>({verification:{status:status==="pending-no-token"?"pending":status,observed:status.startsWith("pending")?null:{...variant.bootIdentity,...(status==="mismatch"?{target:"athom-c3-tubes"}:{})},bytesCaptured:120},retryToken:status==="pending"&&verificationStatus!=="pending-no-token"?Object.freeze({id:"retry"}):null});
	let chipName="ESP32";const flash={setInvalidationHandler(handler){invalidator=handler;},async connectToController(){connects++;if(connectError)throw connectError;return {token:Object.freeze({id:"token"}),port:{id:"port"},chipName,chipFamily:chipName,portInfo:{}};},bindConnectedController({evidence,variant}){return {...evidence,variantId:variant.id};},async installConnectedController(args){installs++;lastArgs=args;args.onStatus("Restarting the controller…");args.onStatus("Verifying the controller…");args.onReceipt({stage:"awaiting-health",targetId:args.variant.id,artifactSha256:args.artifact.sha256});return {sha256:args.artifact.sha256,writeEvidence:"Write call returned",health:"unverified",...resultFor(args.variant,verificationStatus)};},async verifyWrittenController(args){verifies++;lastVerifyArgs=args;return resultFor(args.variant,verificationStatus);},async disconnectController(){disconnects++;}};
	const diagnoseRuntime={async inspect(){inspects++;return {state:"telemetry",target:null,observedTarget:null,chip:"ESP32-C3",button:"AVAILABLE",bytesCaptured:24};}};
	const seedRuntime={bind({targetId,verified}){return targetId==="quinled-dig2go"&&verified?{id:"bound"}:null;},async seed(){seeds++;return {status:"sent",acknowledged:true};}},app=initEasyFlash({document:doc,navigator:{serial:{requestPort(){}}},isSecureContext:true,releaseLoader:async()=>({releaseId:"test",catalog}),flash,diagnoseRuntime,seedRuntime});
	return {doc,app,flash,counts:()=>({installs,verifies,disconnects,inspects}),seedCount:()=>seeds,connectCount:()=>connects,args:()=>lastArgs,verifyArgs:()=>lastVerifyArgs,disconnect:()=>invalidator?.(),setChip:value=>{chipName=value;const id=value==="ESP32"?"quinled-dig2go":value==="ESP32-C3"?"athom-c3-tubes":"waveshare-s3-tubes-remote";(doc.nodes["#deviceOptions"].children||[]).forEach(label=>{const input=label.children?.[0];if(input)input.checked=input.value===id;});doc.nodes["#deviceOptions"].querySelector=()=>({value:id});},setConnectError:value=>connectError=value,setVerification:value=>verificationStatus=value};
}

test("wrong-device recovery reuses the validated connection and keeps writes blocked until target matches",async()=>{const f=fixture();await Promise.resolve();f.setChip("ESP32-S3");f.doc.nodes["#deviceOptions"].querySelector=()=>({value:"athom-c3-tubes"});await f.app.connect();assert.equal(f.doc.nodes["#mismatchFacts"].textContent,"Selected: Athom ESP32-C3 controller · Connected: Waveshare ESP32-S3-Touch-AMOLED-2.16");assert.match(f.doc.nodes["#mismatchReason"].textContent,/canonical firmware/i);assert.equal(f.doc.nodes["#useConnected"].hidden,false);assert.equal(f.counts().installs,0);f.doc.nodes["#useConnected"].dispatch("click");await Promise.resolve();assert.equal(f.connectCount(),1);assert.equal(f.app.getSelection().variant.id,"waveshare-s3-tubes-remote");assert.equal(f.doc.nodes["#controllerStateTitle"].textContent,"ESP32-S3 detected");await f.app.install();assert.equal(f.counts().installs,1);});


test("Advanced updates stays static while Flash state changes",async()=>{const f=fixture(),details=f.doc.nodes["#technicalDetails"];details.children=[{children:[{textContent:"Coming soon"},{textContent:"OTA and nearby-device update tools will live here. For now, use USB Easy Flash above."}]}];const before=JSON.stringify(details.children);await Promise.resolve();await f.app.connect();await f.app.install();assert.equal(JSON.stringify(details.children),before);});

test("single-device ordinary install verifies exact boot identity without public fleet migration state",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();await f.app.install();assert.equal(f.doc.nodes["#resultPanel"].hidden,false);assert.equal(f.doc.nodes["#installTitle"].textContent,"Firmware installed");assert.equal(f.doc.nodes["#resultTitle"].textContent,"You did it!");assert.equal(f.doc.nodes["#resultMessage"].textContent,"Firmware bytes were written successfully. The controller should restart.");assert.match(f.doc.nodes["#resultNext"].textContent,/does not start peer propagation/);assert.equal(f.app.getSelection(),null);for(const selector of ["#migrationCard","#migrationSummary","#otaStateMessage"])assert.equal(f.doc.nodes[selector],undefined);});

test("successful ordinary writer completion reaches Done without restart confirmation",async()=>{const f=fixture();f.setVerification("pending");await Promise.resolve();await f.app.connect();await f.app.install();assert.equal(f.doc.nodes["#resultTitle"].textContent,"You did it!");assert.equal(f.doc.nodes["#resultVerify"].hidden,true);assert.match(f.doc.nodes["#resultNext"].textContent,/does not start peer propagation/);assert.equal(f.counts().verifies,0);});
test("verified ordinary Dig2Go never offers or sends propagation",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();await f.app.install();assert.equal(f.seedCount(),0);assert.equal(f.doc.nodes["#resultSeed"].hidden,true);});
test("propagating install automatically commands the verified Dig2Go after boot",async()=>{const f=fixture();await Promise.resolve();f.doc.nodes["#connectPropagating"].dispatch("click");await new Promise(resolve=>setImmediate(resolve));assert.equal(f.app.getSelection().installMode,"propagating");await f.app.install();assert.equal(f.seedCount(),1);assert.equal(f.doc.nodes["#resultSeed"].hidden,true);assert.match(f.doc.nodes["#resultMessage"].textContent,/installed and running/);assert.match(f.doc.nodes["#resultNext"].textContent,/accepted one serve turn/);});

test("Hooray done resets the chooser without writing and Diagnose stays read-only",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();await f.app.install();f.doc.nodes["#resultDone"].dispatch("click");assert.equal(f.doc.nodes["#resultPanel"].hidden,true);assert.equal(f.doc.nodes["#installTitle"].textContent,"Install firmware");assert.equal(f.doc.nodes["#installCard"],undefined);assert.equal(f.app.getSelection(),null);assert.equal(f.doc.nodes["#connect"].disabled,false);assert.equal(f.doc.activeElement,f.doc.nodes["#connect"]);assert.equal(f.counts().installs,1);f.doc.nodes["#resultDiagnose"].dispatch("click");assert.equal(f.doc.nodes["#diagnoseView"].hidden,false);assert.equal(f.counts().inspects,0);});

test("wrong exact identity reports expected and observed without rewrite",async()=>{const f=fixture();f.setVerification("mismatch");await Promise.resolve();await f.app.connect();await f.app.install();assert.equal(f.doc.nodes["#resultTitle"].textContent,"Installed firmware did not match");assert.equal(f.doc.nodes["#resultDiagnose"].hidden,false);assert.equal(f.counts().installs,1);});

test("Connect is the sole initial primary and each exact target gets one printed-label check",async()=>{for(const [chip,id,label,model] of [["ESP32","quinled-dig2go","Install Dig2Go firmware","QuinLED Dig2Go"],["ESP32-C3","athom-c3-tubes","Install Athom C3 firmware","Athom ESP32-C3 controller"],["ESP32-S3","waveshare-s3-tubes-remote","Install Waveshare S3 firmware","Waveshare ESP32-S3-Touch-AMOLED-2.16"]]){const f=fixture();await Promise.resolve();f.setChip(chip);assert.equal(f.app.getSelection(),null);assert.notEqual(f.doc.nodes["#connect"].className,"secondary");assert.equal(f.doc.nodes["#install"].hidden,true);await f.app.connect();assert.equal(f.app.getSelection().variant.id,id);assert.match(f.app.getSelection().artifact.url,new RegExp(id));assert.equal(f.doc.nodes["#install"].textContent,label);assert.equal(f.doc.nodes["#install"].hidden,false);assert.equal(f.doc.nodes["#install"].disabled,false);assert.equal(f.doc.nodes["#connect"].hidden,true);assert.match(`${f.doc.nodes["#instruction"].textContent} ${f.doc.nodes["#actionNote"].textContent}`,new RegExp(`Confirm the board says ${model}`));assert.equal(`${f.doc.nodes["#instruction"].textContent} ${f.doc.nodes["#actionNote"].textContent}`.match(/Confirm the board says/g)?.length,1);assert.equal(f.doc.nodes["#controllerStateTitle"].textContent,`${chip} detected`);}});

test("unsupported detection fails closed without Install",async()=>{const f=fixture();f.setChip("ESP32-C6");await Promise.resolve();await f.app.connect();assert.equal(f.app.getSelection(),null);assert.equal(f.doc.nodes["#install"].hidden,true);assert.match(f.doc.nodes["#resultMessage"].textContent,/unsupported|does not match/i);});
test("unsupported browser gate disables serial actions but leaves status available",async()=>{const f=fixture();const nav={userAgent:"Mozilla/5.0 Safari/605.1",serial:{requestPort(){}}};initEasyFlash({document:f.doc,navigator:nav,isSecureContext:true,releaseLoader:async()=>({releaseId:"test",catalog:[]}),flash:f.flash,diagnoseRuntime:f.diagnoseRuntime});await Promise.resolve();assert.equal(f.doc.nodes["#browserGate"].hidden,false);assert.equal(f.doc.nodes["#browserGateTitle"].textContent,"Easy Flash needs Chrome or Edge");assert.match(f.doc.nodes["#browserGateMessage"].textContent,/This browser cannot connect/);assert.equal(f.doc.nodes["#connect"].hidden,true);assert.equal(f.doc.nodes["#diagnoseInspect"].hidden,true);assert.equal(f.doc.nodes["#statusTab"].hidden,false);});
test("insecure context gets distinct HTTPS guidance",async()=>{const f=fixture();initEasyFlash({document:f.doc,navigator:{userAgent:"Chrome",serial:{requestPort(){}}},isSecureContext:false,releaseLoader:async()=>({releaseId:"test",catalog:[]}),flash:f.flash,diagnoseRuntime:f.diagnoseRuntime});await Promise.resolve();assert.match(f.doc.nodes["#browserGateMessage"].textContent,/over HTTPS/);assert.doesNotMatch(f.doc.nodes["#browserGateMessage"].textContent,/This browser cannot connect/);});
test("Connect never writes and the exact candidate action admits Install",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();assert.equal(f.counts().installs,0);await f.app.install();assert.equal(f.counts().installs,1);assert.equal(f.args().candidateAction.targetId,"quinled-dig2go");assert.equal(f.args().candidateAction.label,"Install Dig2Go firmware");assert.equal(f.args().candidateAction.artifactSha256,f.app.getSelection()?.artifact.sha256 ?? f.args().artifact.sha256);});

test("tab selection never touches serial and leaving Flash invalidates prepared install state",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();const diagnose=f.doc.nodes["#diagnoseTab"];f.app.selectTab(diagnose);assert.equal(f.app.getSelection(),null);assert.deepEqual(f.counts(),{installs:0,verifies:0,disconnects:0,inspects:0});await f.app.install();assert.equal(f.counts().installs,0);assert.equal(f.doc.nodes["#diagnoseView"].hidden,false);});

test("Status selection dispatches its lazy-load event without touching serial",async()=>{const f=fixture();let selected=0;f.doc.addEventListener("easy-flash:status-selected",()=>selected++);await Promise.resolve();f.app.selectTab(f.doc.nodes["#statusTab"]);assert.equal(selected,1);assert.deepEqual(f.counts(),{installs:0,verifies:0,disconnects:0,inspects:0});await f.app.inspect();assert.deepEqual(f.counts(),{installs:0,verifies:0,disconnects:1,inspects:1});assert.match(f.doc.nodes["#diagnoseFacts"].children.at(-1).textContent,/Captured bytes:/);});

test("keyboard tabs wrap, support Home/End, and keep one tab in order",async()=>{const f=fixture(),tabs=[f.doc.nodes["#flashTab"],f.doc.nodes["#diagnoseTab"],f.doc.nodes["#statusTab"]];tabs[0].dispatch("keydown",{key:"ArrowLeft"});assert.equal(f.doc.activeElement,tabs[2]);assert.equal(tabs[2].tabIndex,0);tabs[2].dispatch("keydown",{key:"Home"});assert.equal(f.doc.activeElement,tabs[0]);tabs[0].dispatch("keydown",{key:"End"});assert.equal(f.doc.activeElement,tabs[2]);});

test("disconnect and reconnect clear stale candidate action state",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();const stale=f.app.getSelection();f.disconnect();assert.equal(f.app.getSelection(),null);await f.app.install();assert.equal(f.counts().installs,0);await f.app.connect();assert.notEqual(f.app.getSelection(),stale);assert.equal(f.doc.nodes["#install"].textContent,"Install Dig2Go firmware");});
test("cancelled reconnect clears stale presentation and leaves no Install",async()=>{const f=fixture();await Promise.resolve();await f.app.connect();assert.match(f.doc.nodes["#instruction"].textContent,/Confirm the board says/i);const error=Object.assign(Error("cancelled"),{name:"NotFoundError"});f.setConnectError(error);await f.app.connect();assert.equal(f.app.getSelection(),null);assert.equal(f.doc.nodes["#install"].hidden,true);assert.equal(f.doc.nodes["#installTitle"].textContent,"Install firmware");assert.doesNotMatch(f.doc.nodes["#instruction"].textContent,/cannot prove|ESP32/i);assert.equal(f.doc.nodes["#technicalDetails"].children,undefined);});

function mockPort({chunks=[],rejectRead=false,hang=false}={}){let released=false,closed=false,cancelled=false,isOpen=false;const reader={async read(){if(rejectRead)throw Error("device disconnected");if(hang)return new Promise(()=>{});const chunk=chunks.shift();return chunk===undefined?{done:true}:{value:new TextEncoder().encode(chunk),done:false};},releaseLock(){released=true;},async cancel(){cancelled=true;}};return {get readable(){return isOpen?{getReader:()=>reader}:null;},async open(options){this.openOptions=options;isOpen=true;},async close(){closed=true;},getInfo:()=>({usbVendorId:1234}),state:()=>({released,closed,cancelled})};}

test("diagnose caps raw bytes before decoding complete UTF-8",async()=>{const result=await createDiagnoseRuntime({serial:{requestPort:async()=>mockPort({chunks:["éXYZ"]})},maxBytes:3}).inspect();assert.equal(result.raw,"éX");assert.equal(result.bytesCaptured,3);});

test("exact rescue/button parsing uses the latest banner and healthy clears STUCK_BUTTON",()=>{assert.equal(parseDiagnosticText("WLED rescue mode active. Flash over serial, or send 'format'/'reboot'.").rescue,true);assert.equal(parseDiagnosticText("AP mode active; no network yet").rescue,false);const result=parseDiagnosticText("WLED button diagnostics: STUCK_BUTTON\nWLED button diagnostics: healthy");assert.equal(result.buttonProblem,false);assert.equal(result.buttonDiagnostics,"healthy");const bounded=parseDiagnosticText("WLEDTUBES_DIAG target=athom-c3-tubes\nWLEDTUBES_DIAG chip=ESP32-C3 tubes=15\nWLEDTUBES_DIAG rescue=INACTIVE\nWLED button diagnostics: AVAILABLE/INACTIVE");assert.equal(bounded.target,"athom-c3-tubes");assert.equal(bounded.chip,"ESP32-C3 tubes=15");assert.equal(bounded.buttonDiagnostics,"available/inactive");assert.equal(bounded.buttonProblem,false);for(const healthy of ["AVAILABLE","INACTIVE","healthy"])assert.equal(parseDiagnosticText(`WLED button diagnostics: ${healthy}`).buttonProblem,false);});

test("exact target reports classify three carriers but generic C3/S3 chips remain Unknown",()=>{for(const name of ["QuinLED Dig2Go","Athom ESP32-C3 controller","Waveshare ESP32-S3-Touch-AMOLED-2.16"])assert.equal(parseDiagnosticText(`model: ${name}`).target,name);for(const chip of ["ESP32-C3","ESP32-S3"])assert.deepEqual([parseDiagnosticText(`chip: ${chip}`).target,parseDiagnosticText(`chip: ${chip}`).targetIdentity],[null,"unknown"]);});

test("timeout, disconnect, and chooser cancellation cleanly stop without writes",async()=>{const timed=mockPort({hang:true}),result=await createDiagnoseRuntime({serial:{requestPort:async()=>timed},timeoutMs:5}).inspect();assert.equal(result.state,"unsupported");assert.deepEqual(timed.state(),{released:true,closed:true,cancelled:true});const disconnected=mockPort({rejectRead:true}),lost=await createDiagnoseRuntime({serial:{requestPort:async()=>disconnected}}).inspect();assert.equal(lost.state,"unsupported");assert.deepEqual(disconnected.state(),{released:true,closed:true,cancelled:false});const error=Object.assign(Error("cancelled"),{name:"NotFoundError"});await assert.rejects(createDiagnoseRuntime({serial:{requestPort:async()=>{throw error;}}}).inspect(),{name:"NotFoundError"});});

test("captured Athom C3 sparse rescue-inactive evidence is healthy only with supported USB identity",()=>{
 const captured={raw:"WLEDTUBES_DIAG rescue=INACTIVE\\n",state:"partial",rescue:false,bytesCaptured:24,portInfo:{usbVendorId:0x303a,usbProductId:0x1001},chip:"ESP32-C3"};
 const view=diagnosePresentation(captured);
 assert.equal(view.label,"Unknown");
 assert.equal(view.summary,"Couldn’t read this controller");
 assert.equal(diagnosePresentation({...captured,portInfo:{usbVendorId:1,usbProductId:2}}).label,"Unknown");
 assert.equal(diagnosePresentation({raw:"garbage",state:"partial",bytesCaptured:24,portInfo:captured.portInfo}).label,"Unknown");
});

test("Diagnose presentation is grounded USB-only copy for every stoplight state",()=>{const cases=[
 [{},["yellow","Unknown","Couldn’t read this controller","Check another controller"]],
  [{bytesCaptured:3},["yellow","Unknown","Couldn’t read this controller","Check another controller"]],
  [{state:"partial",bytesCaptured:24},["yellow","Unknown","Couldn’t read this controller","Check another controller"]],
 [{state:"telemetry",target:"Dig2Go",chip:"ESP32",tubes:15,rescue:false,buttonDiagnostics:"healthy",button:"healthy"},["yellow","Unknown","Couldn’t read this controller","Check another controller"]],
 [{state:"telemetry",target:"Dig2Go",chip:"ESP32",tubes:14,rescue:false,buttonDiagnostics:"healthy",button:"healthy"},["yellow","Unknown","Couldn’t read this controller","Check another controller"]],
 [{state:"rescue",rescue:true},["red","Broke","Rescue mode is active.","Check another controller"]],
 [{buttonProblem:true},["red","Broke","The controller reported a stuck button.","Check another controller"]]
 ];for(const [input,[tone,label,summary,action]] of cases){const view=diagnosePresentation(input);assert.deepEqual([view.tone,view.label,view.summary,view.action],[tone,label,summary,action]);assert.doesNotMatch(`${view.label} ${view.summary} ${view.next}`,/\b(network|lights|LED|telemetry|inspection|retry)\b/i);}});
